typography_spectrum: 0.79397
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.1875
  lightness: 0.5
  saturation: 0.75
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.75711
analytics:
  google: null
  facebook: null
  twitter: null
name: Arc2Shea
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: 'Search & Discover '
description: Search & Discover
purpose: []
